version: '2'

services:
  app: &app_base
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/app
      - ./public:/var/app/public
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      # - redis
    env_file:
      - .env

  postgres:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data

  # redis:
  #   image: redis
  #   volumes:
  #     - ./tmp/data/redis:/var/lib/redis/data

  # test:
  #   <<: *app_base
  #   ports: []
  #   command: guard start --no-bundler-warning --no-interactions
  #   environment:
  #     RACK_ENV: test
  #     RAILS_ENV: test

volumes:
  postgres:
  # redis:
