version: '2'

services:
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/app
      - ./public:/var/app/public
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  cable:
    depends_on:
      - redis
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - 28080:28080
    volumes:
      - .:/var/app
    env_file:
      - .env

  postgres:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:3.2-alpine
    command: redis-server --requirepass yourpassword
    ports:
      - 6379:6379
    volumes:
      - ./tmp/data/redis:/var/lib/redis/data

  sidekiq:
    depends_on:
      - postgres
      - redis
    build: .
    command: sidekiq -C config/sidekiq.yml
    volumes:
      - .:/var/app
    env_file:
      - .env

volumes:
  postgres:
  redis:
