---

development: &default
  secret_key_base:        <%= ENV['SECRET_KEY_BASE'] %>
  aws_access_key_id:      <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key:  <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_s3_region:          <%= ENV['AWS_S3_REGION'] %>
  aws_s3_bucket:          <%= ENV['AWS_S3_BUCKET'] %>
  aws_cloudfront_domain:  <%= ENV['AWS_CLOUDFRONT_DOMAIN'] %>
  azure_ad_client_id:     <%= ENV['AZURE_AD_CLIENT_ID'] %>
  azure_ad_tenant:        <%= ENV['AZURE_AD_TENANT'] %>
  google_api_key:         <%= ENV['GOOGLE_API_KEY'] %>
  google_client_id:       <%= ENV['GOOGLE_CLIENT_ID'] %>
  google_client_secret:   <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  linkedin_client_id:     <%= ENV['LINKEDIN_CLIENT_ID'] %>
  linkedin_client_secret: <%= ENV['LINKEDIN_CLIENT_SECRET'] %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
