---

development: &default
  secret_key_base: <%= ENV['SECRET_TOKEN'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_s3_region: <%= ENV['AWS_S3_REGION'] %>
  aws_s3_bucket: <%= ENV['AWS_S3_BUCKET'] %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
