#!/bin/bash
# Usage: script/ci [command]
# Run the test suite on a Codeship build machine.

# This makes sure the script fails on the first failing command
set -e

# Adding a check so an argument has to be passed to the container
COMMAND=${1:?'You need to pass a command as the first parameter!'}

# Create and init the database
bundle exec rails db:create db:migrate

case $COMMAND in
test)
  bundle exec rails test
  ;;
unit)
  bundle exec rails test test/controllers test/helpers test/mailers test/models test/policies
  ;;
integration)
  bundle exec rails test test/features test/integration
  ;;
seed)
  bundle exec rails db:seed
  ;;
esac
